# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Summary
tagline:          '나의 글'
description:      '잊어버리지 않기 위해 간간히 적어 놓는...'
url:              https://dosp0911.github.io
baseurl:          ""
paginate:         5


github:
  repo:           https://github.com/dosp0911
